version: "3.9"

name: myapi

services:
  api:
    build:
      context: ./todo
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"  # Expose container port 8000 to host port 8000  
    environment:
      - DATABASE_HOST=postgres  # Set environment variable for DB connection
    networks:
      - my-api-net
  postgres:
    image: postgres:latest  # Use the official PostgreSQL image
    environment:
        - POSTGRES_USER=ziakhan
        - POSTGRES_PASSWORD=my_password
        - POSTGRES_DB=mydatabase
    ports:
        - '5433:5432'
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
        - ./data:/var/lib/postgresql/data_csv
    networks:
      - my-api-net

networks:
  my-api-net:  # Define the custom network
